services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ensky
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwertyuiop
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-app:
    build: .
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      postgres:
        condition: service_healthy